new_idea_task:
  description: >
    You are expected to provide a clean, new, creative general idea for a "point of view" video that will be posted 
    on social media.
    Your idea will be used by other agents to create a detailed scenario for the purpose of creating a video with duration of one minute.
    The idea to be created must lead to the creation of a "point of view" video.
    The video is approxematly one minute long and represents most of the times a short story on the daily life of the first person in a specific time era.
  expected_output: >
    An written idea for the pupors of generating a one minute "point of view" video
  agent: idea_creator

scene_creation:
  description: >
    You will be provided with an idea of a short story. Create multiple scenes based on the general idea. 
    The scenes are used to create a one minute "point of view" that represents a short story of the daily life of the first person in a specific time era.
    In each scene mention the theme, time era, backgrounds in a way that is compabtible with the story
  expected_output: >
    A list of scenes and scenarios that are sorted in the order of the provided story
  agent: scene_creator

prompt_creation:
  description: >
    Create a full, clean prompt based on the provided list of scenes.
    The prompt must be usable for the creation of the desired video
  expected_output: >
    A created prompt to be used in video generation tool
  agent: prompt_creator

caption_task:
  description: >
    Create a caption for every scene. The scenes are created by the scene_creation agent and will be provided to you as list of scenes.
    Create a caption of every scene that tells the viewer what is going on in the scene and gives a short concise idea for the viewer about the scene.
  expected_output:
    A list of captions that are consistent to the list of scenes created in scene_creation task


